name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up AVR toolchain
      run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr avr-libc
    - name: Build it
      run: |
        cd src/m2u8
        # Compile the C code
        make
        cd ..
        make
